

import java.awt.Component;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author win-user
 */
public class itemdetails extends javax.swing.JFrame {
private Component frame;
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form itemdetails
     */
    public itemdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Item ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(63, 63, 46, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sale Price");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(52, 152, 57, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Vendor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(65, 234, 44, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bar Code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(236, 63, 56, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Perchus Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 150, 82, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Unit");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(266, 234, 24, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(127, 63, 67, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(127, 152, 67, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(127, 234, 67, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(325, 63, 69, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(325, 152, 69, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(325, 234, 69, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ITEM DETAILS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 20, 115, 17);

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(257, 270, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
conn=MySqlConnect.ConnectDB();
String Sql="Select * from item_details where item_id=? and bar_code=? and sales_price=? and perchus_price=? and vendor=? and unit=?";
pst=conn.prepareStatement(Sql);
pst.setString(1,"5");
pst.setString(2,"L78");
pst.setString(3,"200");
pst.setString(4,"150");
pst.setString(5,"LAHARI");
pst.setString(6,"1");
rs=pst.executeQuery();
pst.setString(1,"8");
pst.setString(2,"p56");
pst.setString(3,"450");
pst.setString(4,"400");
pst.setString(5,"AARSRITHA");
pst.setString(6,"2");
rs=pst.executeQuery();
pst.setString(1,"1");
pst.setString(2,"h84");
pst.setString(3,"120");
pst.setString(4,"100");
pst.setString(5,"SHIVANI");
pst.setString(6,"3");
rs=pst.executeQuery();
pst.setString(1,"4");
pst.setString(2,"k620");
pst.setString(3,"800");
pst.setString(4,"600");
pst.setString(5,"siri");
pst.setString(6,"3");
rs=pst.executeQuery();
pst.setString(1,"4");
pst.setString(2,"bh10");
pst.setString(3,"510");
pst.setString(4,"40");
pst.setString(5,"ramya");
pst.setString(6,"4");
rs=pst.executeQuery();
customerdetails cd=new customerdetails();
cd.setVisible(true);
while(rs.next()){
    System.out.println("Successfully logged in");
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
